New Module win_dns_delegation
ansible-collections/community.windows pull request #196
Opened 2021-02-16 14:18 UTC by sgruber94

### SUMMARY
The win_dns_delegation module manage a Windows Server DNS Zone Delegations

### ISSUE TYPE
New Module Pull Request

### COMPONENT NAME
win_dns_delegation

### ADDITIONAL INFORMATION
Includes Integration Tests - See documentation file for full details on how the module works.

2021-02-17 14:44 UTC, sgruber94 commented
Tests failed, because example.com zone is not  in test env. Is there any favorite DNS zone, I should use?

2021-03-12 02:59 UTC, jborean93 requested changes

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +        NameServer = @{ type = "str" }
Keep options in `snake_case` format, like `name_server`.

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +        IPAddress  = @{ type = "list"; elements = "str" }
Ditto, use `snake_case` for module options; `ip_address`.

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +    $module.FailJson("Failed to get dns delegation zone. $($_.Exception.Message)", $_)
There's not much need to wrap this in a try catch, Ansible will automatically pick up uncaught exception.

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +                $module.FailJson("Failed to add dns delegation zone $($name): $($_.Exception.Message)", $_)
Same here, the try catch isn't really doing much here, just best off leaving it out.

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +                    $module.FailJson("Failed to compare delegation NameServer zone $($name): $($_.Exception.Message)", $_)
Ditto, remove try/catch

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +                    $module.FailJson("Failed to compare delegation NameServer zone $($name): $($_.Exception.Message)", $_)
Ditto, remove try/catch

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +                    $module.FailJson("Failed to change dns Server zone $($name): $($_.Exception.Message)", $_)
Ditto, remove try/catch

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +                $module.Result.changed = $false
Just an FYI, `changed = $false` is the default, you typically only ever need to set this value if you are setting it to `$true`.

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +            $module.FailJson("Failed to add dns delegation zone $($name): $($_.Exception.Message)", $_)
Ditto, remove try/catch

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.ps1
> +    if ($check_mode) { $parms.WhatIf = $check_mode }
You may as well add this to `$parms` when you define it as it's used for both state present and absent. A switch can be set to `$false` as well to indicate it's not set allowing you to do it in all cases and not just in check mode.

2021-03-12 02:59 UTC, jborean93 commented on plugins/modules/win_dns_delegation.py
> +module: win_dns_delegation
Needs `version_added: '1.4.0'.

2021-03-12 02:59 UTC, jborean93 commented on tests/integration/targets/win_dns_delegation/tasks/main.yml
> +- name: ADD | DNS Zone Delegation
This is a very bare set of tests, you should be testing all sorts of scenarios like check mode, state present/absent, idempotency. Not just the modules you should also be checking the results to make sure the module did what you told it to do.

2021-03-12 02:59 UTC, jborean93 commented
For the test failure this is all standalone, you need to setup what is needed to run them.

2021-07-09 20:36 UTC, jborean93 commented
See https://github.com/ansible-collections/community.windows/pull/194#issuecomment-877442730

2021-07-09 20:36 UTC, closed without merging