Enhance documentation for win_scheduled_task module
ansible-collections/community.windows pull request #207
Opened 2021-03-01 17:02 UTC by TheRaspyDev

##### SUMMARY

Compatibility 4 is also valid for Windows Server 2016

##### ISSUE TYPE

- Docs Pull Request

##### COMPONENT NAME

win_scheduled_task

##### ADDITIONAL INFORMATION

```paste below

```

2021-03-11 23:11 UTC, jborean93 requested changes
The rst files on `docs/` are autogenerated from the actual module documentation. You need to update the docs for this module at https://github.com/ansible-collections/community.windows/blob/main/plugins/modules/win_scheduled_task.py#L311. THe rst docs will be updated the next time the collection is updated.

2021-03-15 06:08 UTC, TheRaspyDev commented
Moved documentation to source code

2021-03-15 06:16 UTC, jborean93 approved these changes

2021-03-15 07:49 UTC, merged

2021-03-15 07:50 UTC, jborean93 commented
Thanks for fixing this issue.