New Module: win_domain_ou take 2
ansible-collections/community.windows pull request #278
Opened 2021-07-30 17:54 UTC by gamethis

The win_domain_ou module manages Active Directory Organizational Units (OUs).
ISSUE TYPE

    New Module Pull Request

COMPONENT NAME

win_domain_ou
ADDITIONAL INFORMATION

Includes Integration Tests - See documentation file for full details on how the module works.

2021-08-23 03:22 UTC, jborean93 requested changes
Most of the information here looks good. I do have some concerns with trying to convert the LDAP properties to and from snake_cake. I personally think they should just be as is and have people set the actual LDAP property name in that dict and avoid all the conversions in the module. For example I think `postal_code` should stay as `postalCode` to better reflect the raw nature of `properties`.

What are your thoughts on this?

2021-08-23 03:22 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +author: Joe Zollo (@joezollo), Larry Lane (@gamethis)
Might be best to set this as a list. You also need to add `version_added: 1.7.0` to denote when this was added

```suggestion
version_added: 1.7.0
author:
- Joe Zollo (@joezollo)
- Larry Lane (@gamethis)
```

2021-08-23 03:22 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +      - Defines specific LDAP properties for the organizational unit.
You should describe this a bit more. Currently they are LDAP properties but it looks like the code is trying to convert the values to and from snake and camel case. Personally I think if this is going to be a free form field that it just use the camel case names that are in use with LDAP. It makes it easier for people wanting to set the raw values outside of the root module options without having to translate what they are actually for.

2021-08-23 15:33 UTC, gamethis commented
> Most of the information here looks good. I do have some concerns with trying to convert the LDAP properties to and from snake_cake. I personally think they should just be as is and have people set the actual LDAP property name in that dict and avoid all the conversions in the module. For example I think `postal_code` should stay as `postalCode` to better reflect the raw nature of `properties`.
> 
> What are your thoughts on this?

@jborean93 I was doing that just to try to follow standard ansible fact idea... but yes I actually prefer the other way where it is just a straight up property passthrough.  I will update make the update for this

2021-08-23 18:43 UTC, jborean93 commented
>  I was doing that just to try to follow standard ansible fact idea.

I think if it was root options then using the snake_case is best but in this case it's meant to reflect the raw LDAP properties and reduces confusion so I'm totally fine having it without the translation.

> My question is do we return free form or does it need to be snake_case return of values?

Personally I don't think it should be returning values at all and this should be done under a `win_domain_ou_info` module but my thoughts are the return value should match the input options as closely as it can.

2021-09-16 15:58 UTC, gamethis commented
@jborean93 jborean93 so everything is fixed and working... the server 2016 test failed to ever connect with winrm from beginning... is there a way to rerun that?

2021-09-16 21:07 UTC, gamethis commented
> Most of the information here looks good. I do have some concerns with trying to convert the LDAP properties to and from snake_cake. I personally think they should just be as is and have people set the actual LDAP property name in that dict and avoid all the conversions in the module. For example I think `postal_code` should stay as `postalCode` to better reflect the raw nature of `properties`.
> 
> What are your thoughts on this?
Made the changes

2021-09-16 22:05 UTC, jborean93 reviewed
Just a few minor nits, looks like the doc examples also need to be updated to use the actual LDAP property names rather then the `snake_case` ones that were originally in place.

2021-09-16 22:05 UTC, jborean93 commented on plugins/modules/win_domain_ou.ps1
> +#Requires -Module Ansible.ModuleUtils.CamelConversion
I don't think this is needed anymore right?

2021-09-16 22:05 UTC, jborean93 commented on plugins/modules/win_domain_ou.ps1
> +Catch { $module.FailJson("Line 124: The ActiveDirectory module failed to load properly: $($_.Exception.Message)", $_) }
Probably best to exclude `Line 124` in the error. `FailJson` will provide the stacktrace which includes the line numbers when you provide the error/exception which you have here. Ditto for the rest.

2021-09-16 22:05 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +      - Free form dict of properties for the organizational unit.
It might be best to mention that these follow the `LDAP` property names, like `streetAddress`.

2021-09-16 23:16 UTC, jborean93 commented on plugins/modules/win_domain_ou.ps1
> +$module.Result.properties = $properties
You should avoid doing this as it's a bit superfluous and could expose sensitive information. The `params` are automatically displayed in Ansible when you run with `-vvv` solving that problem and the extras are really just based on those values anyway so the data isn't really needed.

```suggestion
```

2021-09-16 23:16 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +      street_address: 1155 Perimeter Center West
Needs to be updated to use the LDAP form `streetAddress`.

2021-09-16 23:16 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +      postal_code: 30189
Needs to be updated to use the LDAP form `postalCode`.

2021-09-16 23:16 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +      managed_by: jzollo@vmware.com
Needs to be updated to use the LDAP form `managedBy`.

2021-09-16 23:16 UTC, jborean93 commented on plugins/modules/win_domain_ou.py
> +      managed_by:
These also need fixing to reflect that we don't convert to snake_case anymore.

2021-09-23 01:01 UTC, jborean93 approved these changes

2021-09-23 01:02 UTC, merged

2021-09-23 02:05 UTC, jborean93 commented
I've unfortunately had to revert this commit as further testing found some larger problems https://github.com/ansible-collections/community.windows/pull/297. It seems like some of the tests have been written around actual results rather than the proper expectations, testing something had not changed when in reality it should for that scenario.

2021-09-23 13:56 UTC, gamethis commented
I don't fully comprehend the difference in the final test and why it shows different from the other... bu t I think I have found the error in the code that caused it... I will go back and iprove the test and reoopen a pr in next day or so