win_xml: Prevent issue when no childnode is defined
ansible-collections/community.windows pull request #482
Opened 2023-01-09 15:27 UTC by RyanBijkerk

##### SUMMARY
It is not possible to add a new element to an empty element. To prevent this I have added logic to add an element when the node does not contain any childnodes. Please take a look at the additional information for more details and examples.

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
win_xml

##### ADDITIONAL INFORMATION
My goal was to add a simple httpRedirect configuration in an existing web.config of an IIS server. In my example, I only had an empty configuration as by base XML.

Playbook:
```YAML
- name: Create httpRedirect
  win_xml:
    path: C:\inetpub\wwwroot\web.config
    xpath: "/configuration/system.webServer"
    fragment: "<httpRedirect />"
```
Base XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
  </system.webServer>
</configuration>
```

In this example, no changes are made. When adjusting the XML by adding a text element:

Base XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    example
  </system.webServer>
</configuration>
```

Result XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    example
  <httpRedirect /></system.webServer>
</configuration>
```

Behavior when using the pull request adjustment:

Base XML:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
  </system.webServer>
</configuration>
```

Result:
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <system.webServer>
    <httpRedirect />
  </system.webServer>
</configuration>
```

Tested this in two separate environments on both Windows Server 2019 and Windows Server 2022 with the ansible versions: 
2.10.17 & 2.13.7

2023-01-09 15:42 UTC, RyanBijkerk commented
Can someone please explain why these Sanity tests fail?

2023-01-23 03:05 UTC, jborean93 requested changes
Thanks for the PR, it would be great if you could add a changelog fragment to document this bugfix https://docs.ansible.com/ansible/latest/community/development_process.html#creating-a-changelog-fragment.

It would also be great if you could add this scenario to the existing win_xml tests at https://github.com/ansible-collections/community.windows/tree/main/tests/integration/targets/win_xml. Having a test ensures that no future changes will break this particular scenario inadvertently which is key for a module like this.

2023-01-23 03:05 UTC, jborean93 commented on plugins/modules/win_xml.ps1
> +                $elements += $node
Can you just do `$elements = @($node)`?

2023-01-23 10:10 UTC, RyanBijkerk commented on plugins/modules/win_xml.ps1
> +                $elements += $node
Correct! Updated the code.

2023-01-23 10:11 UTC, RyanBijkerk commented
Added both test and change log fragment.

2023-01-23 19:20 UTC, jborean93 approved these changes
Thanks!

2023-01-23 19:20 UTC, merged